FROM python:3.10-slim

# Create a non-root user
RUN useradd -m prime

# Copy the Python script into the container
COPY ./sysnice_test.py /app/sysnice_test.py

# Set the working directory
WORKDIR /app

# Run the script as the non-root user
USER prime

# Command to run the script
CMD ["python", "sysnice_test.py"]
